'use strict';
/**
 * It will make cats galery card example
 */


 // * сюда вставим наши карточки с котиками
 const app = document.querySelector('.app');

 
class CatCard {
    
    constructor(hor, vert) {
        this.hor = hor;
        this.vert = vert;
        this.cat_name = 'Tom Cat';
        this.img_src = `https://placekitten.com/${this.hor}/${this.vert}`;
        this.p_desc = `Это описание кота`;
        this.p_size = `Это размер: ${this.hor}&times;${this.vert}`;
    }

    getCard() {
        return `
<div class="card">
    <img src="${this.img_src}" class="thumb" alt="${this.cat_name}" title="${this.cat_name}">
    <p class="desc">Описание котика</p>
    <p class="size">Размер <b>${this.hor}</b>
    &times;
    <b>${this.vert}</b></p>
</div><!-- /.card .generated by CatCard -->
        `;
    }
}

// let caty1 = new CatCard(201, 151);
// app.insertAdjacentHTML('afterbegin', caty1.getCard());
// console.log(caty1.getCard());


const getRandomInt = Max => Math.floor(Math.random() * Max);

for (let i=0; i<25; i++) {

    let caty3 = new CatCard(160+getRandomInt(50), 100+getRandomInt(50));
    app.insertAdjacentHTML('afterbegin', caty3.getCard());
    console.log(caty3.getCard());

}
 